### ISSUE TITLE
TIGRFAMs source

### ISSUE THREAD

**Issue by xiekunwhy** [PedroMTQ/mantis#20]
Hi,

I found that the latest TIGRFAMs versions is hosted in ncbi genome database, is the mantis pipeline use this latest version https://www.ncbi.nlm.nih.gov/genome/annotation_prok/tigrfams/ ?

Best,
Kun

**Comment by PedroMTQ** [comment]
Hello @xiekunwhy,
It currently uses the TIGRfams from ftp://ftp.tigr.org/pub/data/TIGRFAMs/TIGRFAMs_15.0_HMM.tar.gz
But I'll make sure to update to the latest version. I was not aware NCBI currently hosts them.
Thanks for letting me know.

Regards,
Pedro

**Comment by PedroMTQ** [comment]
Hello @xiekunwhy 
Just checked this. Mantis already uses the data from the link you sent since it uses NCBI's HMMs (which contain TIGRfams).
As also mentioned in the same website, TIGRfams last update was on the 16th of September, 2014 (v15.0), which Mantis currently uses.

In any event, since using both sources is redundant when it comes to TIGRfam HMMs, in the future, I might remove TIGRfam from the default reference download.

Regards,
Pedro
