### ISSUE TITLE
Use NOG database with DIAMOND

### ISSUE THREAD

**Issue by iquasere** [PedroMTQ/mantis#36]
Greetings!

I have not found these informations anywhere, so will ask here:
1. How can I setup a NOG database for use with DIAMOND inside mantis' workflow? By default it seems to get HMMs only, but my system cannot handle the HMM version of NOG because of the size. I have tried using the [refdb_generator](https://github.com/PedroMTQ/refdb_generator), but it only has documentation for HMMs.
2. 1e-3 is the default e-value when using HMMs, am I right? Scaled e-value is only used in homology-based annotation with DIAMOND?
3. In the supplementary PDF of the mantis paper it says ```Wilcoxon signed rank test were performed using the python package Scipy [12], with the function "scipy.stats.wilcoxon"``` . Are the commands used for this analysis available anywhere?

Thank you for your attention

**Comment by PedroMTQ** [comment]
Hello @iquasere ,

Regarding your questions:
-Mantis supports Diamond since v1.1. I believe this is in the wiki, but please let me know if I should further highlight this. When you run `setup_databases`, Mantis will now generate a diamond database instead of using the HMMs (this is a feature we recently added). This is the default behavior but both options are available, it just depends how you setup your MANTIS.config file. Check here for more [info](https://github.com/PedroMTQ/mantis/wiki/Configuration). 

-Regarding the refdb_generator repo. This is a repo that generates additional databases besides the ones in Mantis. They are formatted to be compatible with Mantis, but besides that they are totally independent. This repo is still under development as it's just a small side project. But you are right, the wiki was out of date so I updated it accordingly.

-Regarding the e-value, it is scaled for both methods. Since Mantis splits some databases in chunks we scale the e-value accordingly (using 1e-3  as the baseline), but we also use a dynamic e-value for diamond. If you do set the e-value when you run Mantis, it will be set to a static value, so it won't scale to database size, even if it's split in chunks. So, in general I would avoid setting the e-value, unless you are sure of of the downstream consequences it would have. If you are curious, you can also check the code or ask, and I'll try to explain it further.

-I'm not entirely sure to which specific commands you are referring to. The benchmark methodology and a copy of the code is provided in the "Data Availability" section of the publication. 

Please let me know if you have any other questions or if something is unclear in the wiki.

Regards,
Pedro

**Comment by iquasere** [comment]
Thank you, Pedro, for your answers, I see the ```MANTIS.config``` file now has a default value for the NOG database.

I have encountered an error with the ```setup_databases``` command, however. Following the [quick configuration](https://github.com/PedroMTQ/mantis#quick-configuration), when running the command ```python mantis setup_databases```, I encountered the following error:
```
#  Finished downloading all data!
Extracting sequences from Diamond database
NOG diamond fastas will be extracted with 16 workers!
Creating NOGT diamond databases
Traceback (most recent call last):
  File "/home/jsequeira/anaconda3/envs/mantis_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jsequeira/anaconda3/envs/mantis_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mantis/__main__.py", line 206, in <module>
    setup_databases(force_download=force_download, chunk_size=chunk_size,no_taxonomy=no_taxonomy, mantis_config=mantis_config,cores=cores)
  File "mantis/source/Assembler.py", line 19, in setup_databases
    mantis.setup_databases(force_download)
  File "mantis/source/utils.py", line 587, in wrapper
    res = f(self, *args, **kwargs)
  File "mantis/source/Database_generator.py", line 77, in setup_databases
    self.compile_NOGT_DMND(force_download)
  File "mantis/source/Database_generator.py", line 1233, in compile_NOGT_DMND
    run_command(f'{DIAMOND_PATH} makedb --in {taxon_faa} -d {taxon_dmnd}')
NameError: name 'taxon_faa' is not defined
```
This is likely because of a typo, ```taxon_faa``` should be ```taxon_fasta``` in [here](https://github.com/PedroMTQ/mantis/blob/master/source/Database_generator.py#L1233), correct? I'll edit it and see if I can finish this step.

**Comment by iquasere** [comment]
Yup, it finishes successfully! ^^

**Comment by PedroMTQ** [comment]
Hello @iquasere 

Sorry for the delay. I'm glad you fixed it yourself, I had done some refactoring and I must have missed that.
Anyway, let me know if you have any more questions, otherwise I'll close the issue.

Regards,
Pedro

**Comment by PedroMTQ** [comment]
Hello @iquasere 
In the end, did you manage to use the refdb_generator repo? I've only tested them locally, so I would be interested to know if other people successfully used them.

Regards,
Pedro

**Comment by iquasere** [comment]
No, I only ran ```setup_databases``` as described in base usage

**Comment by PedroMTQ** [comment]
Ah ok, since you mentioned the repo I thought you were planning on using one of those additional databases.

\Pedro

**Comment by iquasere** [comment]
Hi there! Regarding the ```quality_benchmark.py``` script from the scripts of the mantis paper, I was wondering how do you use the ```alignment_prokka.m8``` after it is obtained? I don't see reference to it anywhere in the following lines of the script, and would like to know how you handled wrong DIAMOND assignments (i.e. when you obtain less unique ```sseqids``` than ```qseqids``` because DIAMOND erroniously assigned the same annotation to different queries.

**Comment by PedroMTQ** [comment]
Hello @iquasere 

Check the `read_alignment_output` function.

Regards,
Pedro
