### ISSUE TITLE
TaxID requirements for MANTIS

### ISSUE THREAD

**Issue by susheelbhanu** [PedroMTQ/mantis#9]
Hey @PedroMTQ, 

I'm running MANTIS like so
`python run_mantis -t {input.TSV} --output_folder $(dirname {output}) --mantis_config {input.config}`

and ran into the following issue
```
Could not find taxa ID for MAGS
#  Splitting samples into chunks!
#  Samples will be split into 9651 chunks with 112 workers
#  Running HMMER with 112 workers.
```

Can one provide GTDBtk data or is this pulled from NCBI? It looked like it failed due to connection issues. My `TSV` files like so.
```
GL_R10_GL11_UP_3_G2.2.1.1       /mnt/data/sbusi/rock_mantis/results/prokka/GL_R10_GL11_UP_3_G2.2.1.1/GL_R10_GL11_UP_3_G2.2.1.1.faa      MAGS
GL_R10_GL11_UP_3_maxbin_res.008.fasta_sub       /mnt/data/sbusi/rock_mantis/results/prokka/GL_R10_GL11_UP_3_maxbin_res.008.fasta_sub/GL_R10_GL11_UP_3_maxbin_res.008.fasta_sub.faa      MAGS
GL_R10_GL11_UP_3_maxbin_res.019.fasta_sub       /mnt/data/sbusi/rock_mantis/results/prokka/GL_R10_GL11_UP_3_maxbin_res.019.fasta_sub/GL_R10_GL11_UP_3_maxbin_res.019.fasta_sub.faa      MAGS
GL_R10_GL11_UP_3_O7     /mnt/data/sbusi/rock_mantis/results/prokka/GL_R10_GL11_UP_3_O7/GL_R10_GL11_UP_3_O7.faa  MAGS
GL_R11_GL15_UP_1_B1.1.1.1.1.1   /mnt/data/sbusi/rock_mantis/results/prokka/GL_R11_GL15_UP_1_B1.1.1.1.1.1/GL_R11_GL15_UP_1_B1.1.1.1.1.1.faa      MAGS
```

Thanks for your help!

**Comment by PedroMTQ** [comment]
Hey @susheelbhanu,
The TSV file format is incorrect! It should be something like this:
https://github.com/PedroMTQ/mantis/blob/master/tests/test_file.tsv

So, file name, followed by file path and then taxonomy.
Keep in mind we don't currently use GTDBtk, but NCBI taxon IDs, so that's why Mantis could not find the taxonomic lineage.

Regards,
Pedro

**Comment by susheelbhanu** [comment]
Is it necessary that one provide taxIDs always? Can it run without it?

**Comment by PedroMTQ** [comment]
Yes, it can run without it. Doing so will not use all of the taxa-specific HMMs.
This really depends on your data though, if you know your MAGs are well characterized/not novel then using taxa-specific HMMs **generally**(but not guaranteed) provides better results. Novel MAGs won't really benefit from them since the reference data is most likely of poor quality anyway.

Regards,
Pedro

**Comment by susheelbhanu** [comment]
Excellent - thank you!
